# **Traffic Incidents optimization**

## **Context**

## **Objectives**

## **Model formulation**

## **Model implementation**

### Imports

In [1]:
import cvxpy as cp
import numpy as np
np.set_printoptions(precision=3, suppress=True)

First step is to maximize the severities of the incidents under current response resources(Number of available agents)

In [2]:
i = 3 # number of agents
j = 5  # number of incidents

b = np.array([1, 2, 3, 2, 1]) # agents needed per incidents

x = cp.Variable((i, j), boolean=True) # agents-incidents matrix
z = cp.Variable(j, boolean=True) # incidents coverage vector

objective = cp.Maximize(b@z) 

constraints = [cp.sum(x, axis=0) >= cp.multiply(b, z), # required agents per incidents
               cp.sum(x, axis=1) <= 1 # one agent covers at max. one incident
               ]
               
problem = cp.Problem(objective, constraints)

problem.solve()

3.0

In [3]:
print("Priotities\n", b, end="\n\n")
print("Agents :\n", x.value, end="\n\n")
print("Incidents:\n", z.value, end="\n\n")

Priotities
 [1 2 3 2 1]

Agents :
 [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]

Incidents:
 [0. 0. 1. 0. 0.]



Next step is to minize the total travel time of all the agents

In [37]:
t = np.random.random((i, j)) 

print(x)
objective = cp.Minimize(cp.sum(cp.sum(cp.multiply(x, t), axis=0)))


constraints = [cp.sum(x, axis=0) >= b@z.value, # required agents per incidents
               cp.sum(x, axis=1) <= 1 # one agent covers at max. one incident
               ]
               
problem = cp.Problem(objective, constraints)

problem.solve(solver="ECOS_BB",) #verbose=True)

var37


inf

## **Model in practice**