# **Traffic Incidents optimization**

## **Context**

## **Objectives**

## **Model formulation**

## **Model implementation**

Imports

In [4]:
import cvxpy as cp
import numpy as np
import pandas as pd
# np.set_printoptions(precision=3, suppress=True)

First step is to maximize the severities of the incidents under current response resources(Number of available agents)

In [5]:
i = 3 # number of agents
j = 5  # number of incidents

b = np.array([1, 2, 3, 2, 1]) # agents needed per incidents

In [6]:
print("Agents needed:\n", b, end="\n")

Agents needed:
 [1 2 3 2 1]


In [7]:
x = cp.Variable((i, j), boolean=True) # agents-incidents matrix
z = cp.Variable(j, boolean=True) # incidents coverage vector

objective = cp.Maximize(b@z) 

constraints = [cp.sum(x, axis=0) >= cp.multiply(b, z), # required agents per incidents
               cp.sum(x, axis=1) <= 1 # one agent covers at max. one incident
               ]
               
problem = cp.Problem(objective, constraints)

problem.solve(verbose=1)

                                     CVXPY                                     
                                     v1.2.1                                    
(CVXPY) Jun 29 10:26:54 AM: Your problem has 20 variables, 2 constraints, and 0 parameters.
(CVXPY) Jun 29 10:26:54 AM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Jun 29 10:26:54 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Jun 29 10:26:54 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.


SolverError: 

                    You need a mixed-integer solver for this model. Refer to the documentation
                        https://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs
                    for discussion on this topic.

                    Quick fix 1: if you install the python package CVXOPT (pip install cvxopt),
                    then CVXPY can use the open-source mixed-integer linear programming
                    solver `GLPK`. If your problem is nonlinear then you can install SCIP
                    (pip install pyscipopt).

                    Quick fix 2: you can explicitly specify solver='ECOS_BB'. This may result
                    in incorrect solutions and is not recommended.
                

In [ ]:
print("Agents :\n", x.value, end="\n\n")
print("Incidents:\n", z.value)

Agents :
 [[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]

Incidents:
 [0. 0. 1. 0. 0.]


Next step is to minize the total travel time of all the agents

In [ ]:
t = pd.read_csv("durations.csv")
t

NameError: name 'pd' is not defined

In [ ]:
objective = cp.Minimize(cp.sum(cp.sum(cp.multiply(x, t), axis=0)))


constraints = [cp.sum(x, axis=0) >= cp.multiply(b, z.value), # required agents per incidents
               cp.sum(x, axis=1) <= 1 # one agent covers at max. one incident
               ]
               
problem = cp.Problem(objective, constraints)

problem.solve()

1.693996824207376

In [ ]:
x.value

array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

## **Model in practice**

In [ ]:
import pandas as pd

In [ ]:
agents = pd.read_csv("agents_may.csv")
incidents = pd.read_csv("incidents_may.csv")

In [ ]:
incidents.head()

id source    type    state  priority gravity      class object  \
0  57518   NUSE  Choque  Cerrado         2  Simple  Siniestro    NaN   
1  57518   NUSE  Choque  Cerrado         2  Simple  Siniestro    NaN   
2  57519   NUSE  Choque  Cerrado         1  Simple  Siniestro    NaN   
3  57519   NUSE  Choque  Cerrado         1  Simple  Siniestro    NaN   
4  57519   NUSE  Choque  Cerrado         1  Simple  Siniestro    NaN   

   latitude  longitude  ...                     address zone_id       orient  \
0  4.705279 -74.127686  ...      Carrera 110 Calle 69 B  Zona 1  Sur - Norte   
1  4.705279 -74.127686  ...      Carrera 110 Calle 69 B  Zona 1  Sur - Norte   
2  4.600571 -74.143379  ...  Carrera 68I Calle 43 B SUR  Zona 2  Norte - sur   
3  4.600571 -74.143379  ...  Carrera 68I Calle 43 B SUR  Zona 2  Norte - sur   
4  4.600571 -74.143379  ...  Carrera 68I Calle 43 B SUR  Zona 2  Norte - sur   

         incident_time incident_day incident_weekday incident_hour  \
0  2022-04-30 23:59:00           30                5            23   
1  2022-04-30 23:59:00           30                5            23   
2  2022-04-30 23:54:00           30                5            23   
3  2022-04-30 23:54:00           30                5            23   
4  2022-04-30 23:54:00           30                5            23   

   implicated_type  injured_count  dead_count  
0        Automóvil            0.0         0.0  
1        Automóvil            0.0         0.0  
2        Automóvil            0.0         0.0  
3        Automóvil            0.0         0.0  
4        Automóvil            0.0         0.0  

[5 rows x 23 columns]

In [ ]:
agents.head()

id           dev_id            read_time           time_stamp  \
0  1651381596  868033050089715  2022-05-01 00:06:36  2022-05-01 00:01:40   
1  1651381596  868033050102534  2022-05-01 00:06:36  2022-05-01 00:01:42   
2  1651381596  868033050090085  2022-05-01 00:06:36  2022-05-01 00:01:47   
3  1651381596  868033050103508  2022-05-01 00:06:36  2022-05-01 00:01:52   
4  1651381596  868033050101650  2022-05-01 00:06:36  2022-05-01 00:01:55   

      speed grp_name           localidad  latitude  longitude  devicegroupid  
0  0.053087      S60  RAFAEL URIBE URIBE  4.551646 -74.108515              6  
1  0.000000      S60             KENNEDY  4.650030 -74.147322              6  
2  0.000000      S60  RAFAEL URIBE URIBE  4.581688 -74.128348              6  
3  0.000000      S60      CIUDAD BOLIVAR  4.551098 -74.147635              6  
4  0.000000      S60             KENNEDY  4.619840 -74.159668              6